renamed the file for mod.rs creation; added logs for outcomes

diff --git a/mk-mod b/mk-mod
--- a/mk-mod
+++ b/mk-mod
@@ -1,5 +1,4 @@
 #!/bin/zsh
-
 rm mod.rs 2>&-
 
 for file in *.rs; do
@@ -8,3 +7,10 @@ for file in *.rs; do
         echo "pub mod $module_name;" >> mod.rs
     fi
 done
+
+if [[ $? === 0 ]]; then
+    echo "Success: created a mod.rs in $(pwd) with:"
+    echo "$(cat mod.rs)"
+else
+    echo "Failed to create mod.rs in $(pwd)!"
+fi
